### ISSUE TITLE
Wrong place for printCoins

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-masty123#1]
This method should not be a part of Coin class.

https://github.com/OOP2018/coinpurse-masty123/blob/f10a927ca3c9d428ca297bd73e360e3a94d02466/src/coinpurse/Coin.java#L62-L70

**Comment by masty123** [comment]
Moved to Purse.java thanks.

**Comment by taveratch** [comment]
Actually, it should be in MoneyUtils.
It has nothing to do with Purse or Coin. It's just utility method.

**Comment by masty123** [comment]
Thanks, I have deleted the printCoin in Purse class because it was already in the MoneyUtil class
