### ISSUE TITLE
Useless exceptions

### ISSUE THREAD

**Issue by chinnonae** [OOP2018/coinpurse-masty123#16]
Exception should have a message that tell something about what happened.

https://github.com/OOP2018/coinpurse-masty123/blob/21d0879a76d9e5a8ecf722046f16ac10275b7941/src/coinpurse/ThaiMoneyFactory.java#L21

https://github.com/OOP2018/coinpurse-masty123/blob/21d0879a76d9e5a8ecf722046f16ac10275b7941/src/coinpurse/MalayMoneyFactory.java#L20

**Comment by masty123** [comment]
Fixed, added the message
